
all:
	$(MAKE) -C drawing $@
	$(MAKE) -C window $@
	$(MAKE) -C ini $@

clean:
	$(MAKE) -C drawing $@
	$(MAKE) -C window $@
	$(MAKE) -C ini $@

fclean:
	$(MAKE) -C drawing $@
	$(MAKE) -C window $@
	$(MAKE) -C ini $@

re:
	$(MAKE) -C drawing $@
	$(MAKE) -C window $@
	$(MAKE) -C ini $@
