
all:
	$(MAKE) -C drawing $@
	$(MAKE) -C ini $@
	$(MAKE) -C refresh $@
	$(MAKE) -C window $@

clean:
	$(MAKE) -C drawing $@
	$(MAKE) -C ini $@
	$(MAKE) -C refresh $@
	$(MAKE) -C window $@

fclean:
	$(MAKE) -C drawing $@
	$(MAKE) -C ini $@
	$(MAKE) -C refresh $@
	$(MAKE) -C window $@

re:
	$(MAKE) -C drawing $@
	$(MAKE) -C ini $@
	$(MAKE) -C refresh $@
	$(MAKE) -C window $@
